export const IPC = {
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  CLAUDE_DETECT: 'claude:detect',
  CLAUDE_PICK_PATH: 'claude:pick-path',
  CLAUDE_LOGIN: 'claude:login',
  LIBRARY_LIST: 'library:list',
  RUN_START: 'run:start',
  RUN_CANCEL: 'run:cancel',
  RUN_EVENT: 'run:event',
  RUN_LOG: 'run:log',
  WORKSPACE_READ_BRIEF: 'workspace:read-brief',
  SHELL_OPEN_EXTERNAL: 'shell:open-external',
  SHELL_OPEN_FILE: 'shell:open-file',
} as const
